# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-08 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20170708_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseresource',
            name='name',
            field=models.CharField(max_length=100, verbose_name='\u8bfe\u7a0b\u8d44\u6e90'),
        ),
    ]
