# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-25 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_auto_20170725_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='teacher_tell',
            field=models.CharField(default='', max_length=500, verbose_name='\u8001\u5e08\u544a\u77e5'),
        ),
        migrations.AddField(
            model_name='course',
            name='youneed_know',
            field=models.CharField(default='', max_length=500, verbose_name='\u8bfe\u7a0b\u987b\u77e5'),
        ),
    ]
